In [ ]:
import pandas as pd

1. Crea un dataframe con el dataset asignado

In [ ]:
df_CS = pd.read_csv ('/content/drive/MyDrive/Clase Titla/csgo_round_snapshots.csv')

2. Muestra los tipos de datos del df

In [ ]:
df_CS.dtypes

time_left                    float64
ct_score                     float64
t_score                      float64
map                           object
bomb_planted                    bool
                              ...
ct_grenade_molotovgrenade    float64
t_grenade_molotovgrenade     float64
ct_grenade_decoygrenade      float64
t_grenade_decoygrenade       float64
round_winner                  object
Length: 97, dtype: object

In [ ]:
df_CS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object
 4   bomb_planted                  122410 non-null  bool
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-null  float64
 13  ct_defuse_kits                122410 non-null  float64
 14  ct_players_alive              122410 non-null  float64
 15  t_players_alive               122410 non-null  float64
 16  ct_weapon_ak47                122410 non-null  float64
 17  t_weapon_ak47                 122410 non-null  float64
 18  ct_weapon_aug                 122410 non-null  float64
 19  t_weapon_aug                  122410 non-null  float64
 20  ct_weapon_awp                 122410 non-null  float64
 21  t_weapon_awp                  122410 non-null  float64
 22  ct_weapon_bizon               122410 non-null  float64
 23  t_weapon_bizon                122410 non-null  float64
 24  ct_weapon_cz75auto            122410 non-null  float64
 25  t_weapon_cz75auto             122410 non-null  float64
 26  ct_weapon_elite               122410 non-null  float64
 27  t_weapon_elite                122410 non-null  float64
 28  ct_weapon_famas               122410 non-null  float64
 29  t_weapon_famas                122410 non-null  float64
 30  ct_weapon_g3sg1               122410 non-null  float64
 31  t_weapon_g3sg1                122410 non-null  float64
 32  ct_weapon_galilar             122410 non-null  float64
 33  t_weapon_galilar              122410 non-null  float64
 34  ct_weapon_glock               122410 non-null  float64
 35  t_weapon_glock                122410 non-null  float64
 36  ct_weapon_m249                122410 non-null  float64
 37  t_weapon_m249                 122410 non-null  float64
 38  ct_weapon_m4a1s               122410 non-null  float64
 39  t_weapon_m4a1s                122410 non-null  float64
 40  ct_weapon_m4a4                122410 non-null  float64
 41  t_weapon_m4a4                 122410 non-null  float64
 42  ct_weapon_mac10               122410 non-null  float64
 43  t_weapon_mac10                122410 non-null  float64
 44  ct_weapon_mag7                122410 non-null  float64
 45  t_weapon_mag7                 122410 non-null  float64
 46  ct_weapon_mp5sd               122410 non-null  float64
 47  t_weapon_mp5sd                122410 non-null  float64
 48  ct_weapon_mp7                 122410 non-null  float64
 49  t_weapon_mp7                  122410 non-null  float64
 50  ct_weapon_mp9                 122410 non-null  float64
 51  t_weapon_mp9                  122410 non-null  float64
 52  ct_weapon_negev               122410 non-null  float64
 53  t_weapon_negev                122410 non-null  float64
 54  ct_weapon_nova                122410 non-null  float64
 55  t_weapon_nova                 122410 non-null  float64
 56  ct_weapon_p90                 122410 non-null  float64
 57  t_weapon_p90                  122410 non-null  float64
 58  ct_weapon_r8revolver          122410 non-null  float64
 59  t_weapon_r8revolver           122410 non-null  float64
 60  ct_weapon_sawedoff            122410 non-null  float64
 61  t_weapon_sawedoff             122410 non-null  float64
 62  ct_weapon_scar20              122410 non-null  float64
 63  t_weapon_scar20               122410 non-null  float64
 64  ct_weapon_sg553               122410 non-null  float64
 65  t_weapon_sg553                122410 non-null  float64
 66  ct_weapon_ssg08               122410 non-null  float64
 67  t_weapon_ssg08                122410 non-null  float64
 68  ct_weapon_ump45               122410 non-null  float64
 69  t_weapon_ump45                122410 non-null  float64
 70  ct_weapon_xm1014              122410 non-null  float64
 71  t_weapon_xm1014               122410 non-null  float64
 72  ct_weapon_deagle              122410 non-null  float64
 73  t_weapon_deagle               122410 non-null  float64
 74  ct_weapon_fiveseven           122410 non-null  float64
 75  t_weapon_fiveseven            122410 non-null  float64
 76  ct_weapon_usps                122410 non-null  float64
 77  t_weapon_usps                 122410 non-null  float64
 78  ct_weapon_p250                122410 non-null  float64
 79  t_weapon_p250                 122410 non-null  float64
 80  ct_weapon_p2000               122410 non-null  float64
 81  t_weapon_p2000                122410 non-null  float64
 82  ct_weapon_tec9                122410 non-null  float64
 83  t_weapon_tec9                 122410 non-null  float64
 84  ct_grenade_hegrenade          122410 non-null  float64
 85  t_grenade_hegrenade           122410 non-null  float64
 86  ct_grenade_flashbang          122410 non-null  float64
 87  t_grenade_flashbang           122410 non-null  float64
 88  ct_grenade_smokegrenade       122410 non-null  float64
 89  t_grenade_smokegrenade        122410 non-null  float64
 90  ct_grenade_incendiarygrenade  122410 non-null  float64
 91  t_grenade_incendiarygrenade   122410 non-null  float64
 92  ct_grenade_molotovgrenade     122410 non-null  float64
 93  t_grenade_molotovgrenade      122410 non-null  float64
 94  ct_grenade_decoygrenade       122410 non-null  float64
 95  t_grenade_decoygrenade        122410 non-null  float64
 96  round_winner                  122410 non-null  object
dtypes: bool(1), float64(94), object(2)
memory usage: 89.8+ MB

3. Muestra las 10 primeras filas

In [ ]:
df_CS.head(10)

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
0,175.00,0.0,0.0,de_dust2,False,500.0,500.0,0.0,0.0,4000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
1,156.03,0.0,0.0,de_dust2,False,500.0,500.0,400.0,300.0,600.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
2,96.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
3,76.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
4,174.97,1.0,0.0,de_dust2,False,500.0,500.0,192.0,0.0,18350.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
5,114.97,1.0,0.0,de_dust2,False,500.0,500.0,500.0,0.0,1750.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,CT
6,94.97,1.0,0.0,de_dust2,False,295.0,111.0,296.0,0.0,1700.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
7,74.97,1.0,0.0,de_dust2,False,295.0,111.0,296.0,0.0,1700.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
8,54.97,1.0,0.0,de_dust2,False,249.0,89.0,269.0,0.0,2300.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
9,174.97,2.0,0.0,de_dust2,False,500.0,500.0,196.0,0.0,19800.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT

4. Muestra las 10 últimas filas

In [ ]:
df_CS.tail(10)

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
122400,0.24,11.0,13.0,de_train,True,119.0,178.0,182.0,195.0,2300.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122401,174.93,11.0,14.0,de_train,False,500.0,500.0,176.0,177.0,11800.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122402,114.93,11.0,14.0,de_train,False,500.0,500.0,476.0,477.0,500.0,...,5.0,4.0,5.0,1.0,0.0,0.0,5.0,0.0,0.0,T
122403,94.93,11.0,14.0,de_train,False,500.0,500.0,476.0,477.0,500.0,...,2.0,3.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,T
122404,35.41,11.0,14.0,de_train,True,315.0,428.0,382.0,467.0,150.0,...,2.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122405,15.41,11.0,14.0,de_train,True,200.0,242.0,195.0,359.0,100.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122406,174.93,11.0,15.0,de_train,False,500.0,500.0,95.0,175.0,11500.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122407,114.93,11.0,15.0,de_train,False,500.0,500.0,495.0,475.0,1200.0,...,4.0,3.0,5.0,1.0,0.0,0.0,5.0,0.0,0.0,T
122408,94.93,11.0,15.0,de_train,False,500.0,500.0,495.0,475.0,1200.0,...,5.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0,T
122409,74.93,11.0,15.0,de_train,False,375.0,479.0,395.0,466.0,1100.0,...,3.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0,T

5. Muestra 15 filas de forma aleatoria (sample)

In [ ]:
df_CS.sample(15)

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
106743,94.93,7.0,11.0,de_nuke,False,138.0,194.0,247.0,197.0,10550.0,...,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,T
63468,174.95,1.0,0.0,de_mirage,False,500.0,500.0,256.0,0.0,18400.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
90059,74.91,1.0,0.0,de_train,False,256.0,86.0,298.0,95.0,1600.0,...,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,CT
14533,94.94,11.0,0.0,de_mirage,False,347.0,495.0,388.0,497.0,45750.0,...,4.0,2.0,2.0,3.0,0.0,0.0,1.0,0.0,0.0,T
116909,33.98,13.0,14.0,de_train,False,341.0,297.0,380.0,300.0,21800.0,...,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,CT
86824,174.95,6.0,3.0,de_inferno,False,500.0,500.0,297.0,100.0,20950.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
95528,174.95,6.0,0.0,de_nuke,False,500.0,500.0,396.0,0.0,35250.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
16045,114.92,3.0,4.0,de_mirage,False,500.0,500.0,197.0,440.0,12050.0,...,5.0,1.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0,T
35606,114.91,1.0,0.0,de_vertigo,False,500.0,500.0,500.0,0.0,750.0,...,0.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,CT
86408,94.91,9.0,13.0,de_train,False,500.0,500.0,500.0,500.0,4200.0,...,5.0,5.0,3.0,3.0,0.0,0.0,3.0,0.0,0.0,CT
105353,94.90,3.0,4.0,de_inferno,False,500.0,500.0,474.0,493.0,5600.0,...,4.0,4.0,4.0,2.0,0.0,0.0,4.0,0.0,0.0,T
32666,74.95,2.0,0.0,de_mirage,False,344.0,456.0,390.0,90.0,6250.0,...,0.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,T
42467,174.97,4.0,9.0,de_dust2,False,500.0,500.0,0.0,91.0,31950.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T
90269,54.91,6.0,2.0,de_train,False,400.0,57.0,388.0,100.0,17850.0,...,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,CT
100088,175.00,11.0,4.0,de_train,False,500.0,500.0,400.0,300.0,600.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT

6.Asigna en la variable n_filas y en n_col el total de filas y el total de columnas que
tiene el df

In [ ]:
n_filas = df_CS.shape[0]
n_col = df_CS.shape[1]

print(f"total de filas: {n_filas}")
print(f"total de columnas: {n_col}")

total de filas: 122410
total de columnas: 97

7. Aplica el formato a los títulos de columnas el formato correcto

In [ ]:
new_col_names = []

for old_name in df_CS.columns:
    name_stripped = old_name.strip()
    name_lowered = name_stripped.lower()
    name_no_spaces = name_lowered.replace(' ', '')
    new_col_names.append(name_no_spaces)
df_CS.columns = new_col_names

print(df_CS.columns)

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev', 'ct_weapon_nova', 't_weapon_nova',
       'ct_weapon_p90', 't_weapon_p90', 'ct_weapon_r8revolver',
       't_weapon_r8revolver', 'ct_weapon_sawedoff', 't_weapon_sawedoff',
       'ct_weapon_scar20', 't_weapon_scar20', 'ct_weapon_sg553',
       't_weapon_sg553', 'ct_weapon_ssg08', 't_weapon_ssg08',
       'ct_weapon_ump45', 't_weapon_ump45', 'ct_weapon_xm1014',
       't_weapon_xm1014', 'ct_weapon_deagle', 't_weapon_deagle',
       'ct_weapon_fiveseven', 't_weapon_fiveseven', 'ct_weapon_usps',
       't_weapon_usps', 'ct_weapon_p250', 't_weapon_p250', 'ct_weapon_p2000',
       't_weapon_p2000', 'ct_weapon_tec9', 't_weapon_tec9',
       'ct_grenade_hegrenade', 't_grenade_hegrenade', 'ct_grenade_flashbang',
       't_grenade_flashbang', 'ct_grenade_smokegrenade',
       't_grenade_smokegrenade', 'ct_grenade_incendiarygrenade',
       't_grenade_incendiarygrenade', 'ct_grenade_molotovgrenade',
       't_grenade_molotovgrenade', 'ct_grenade_decoygrenade',
       't_grenade_decoygrenade', 'round_winner'],
      dtype='object')

8. Crea 8 ejercicios con la indexación por coordenadas

In [ ]:
# 1. Una celda
ej_1 = df_CS.loc[7, 'time_left']
print(ej_1,)

74.97

In [ ]:
# 2. Una columna
ej_2 = df_CS.loc[:, 'ct_score']
print(ej_2)

0          0.0
1          0.0
2          0.0
3          0.0
4          1.0
          ...
122405    11.0
122406    11.0
122407    11.0
122408    11.0
122409    11.0
Name: ct_score, Length: 122410, dtype: float64

In [ ]:
# 3. Columnas múltiples
ej_3 = df_CS.loc[:, ['time_left', 'ct_score']]
print(ej_3)

        time_left  ct_score
0          175.00       0.0
1          156.03       0.0
2           96.03       0.0
3           76.03       0.0
4          174.97       1.0
...           ...       ...
122405      15.41      11.0
122406     174.93      11.0
122407     114.93      11.0
122408      94.93      11.0
122409      74.93      11.0

[122410 rows x 2 columns]

In [ ]:
# 4. Múltiples columnas consecutivas
ej_4 = df_CS.loc[:, 'time_left':'ct_score']
print(ej_4)

        time_left  ct_score
0          175.00       0.0
1          156.03       0.0
2           96.03       0.0
3           76.03       0.0
4          174.97       1.0
...           ...       ...
122405      15.41      11.0
122406     174.93      11.0
122407     114.93      11.0
122408      94.93      11.0
122409      74.93      11.0

[122410 rows x 2 columns]

In [ ]:
# 5. Una fila
ej_5 = df_CS.loc[1]
print(ej_5)

time_left                      156.03
ct_score                          0.0
t_score                           0.0
map                          de_dust2
bomb_planted                    False
                               ...
ct_grenade_molotovgrenade         0.0
t_grenade_molotovgrenade          0.0
ct_grenade_decoygrenade           0.0
t_grenade_decoygrenade            0.0
round_winner                       CT
Name: 1, Length: 97, dtype: object

In [ ]:
# 6. Todas las filas, empezando por la fila 1
ej_6 = df_CS.loc[1:]
print(ej_6)

        time_left  ct_score  t_score       map  bomb_planted  ct_health  \
1          156.03       0.0      0.0  de_dust2         False      500.0
2           96.03       0.0      0.0  de_dust2         False      391.0
3           76.03       0.0      0.0  de_dust2         False      391.0
4          174.97       1.0      0.0  de_dust2         False      500.0
5          114.97       1.0      0.0  de_dust2         False      500.0
...           ...       ...      ...       ...           ...        ...
122405      15.41      11.0     14.0  de_train          True      200.0
122406     174.93      11.0     15.0  de_train         False      500.0
122407     114.93      11.0     15.0  de_train         False      500.0
122408      94.93      11.0     15.0  de_train         False      500.0
122409      74.93      11.0     15.0  de_train         False      375.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
1          500.0     400.0    300.0     600.0  ...                  0.0
2          400.0     294.0    200.0     750.0  ...                  0.0
3          400.0     294.0    200.0     750.0  ...                  0.0
4          500.0     192.0      0.0   18350.0  ...                  0.0
5          500.0     500.0      0.0    1750.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122405     242.0     195.0    359.0     100.0  ...                  2.0
122406     500.0      95.0    175.0   11500.0  ...                  2.0
122407     500.0     495.0    475.0    1200.0  ...                  4.0
122408     500.0     495.0    475.0    1200.0  ...                  5.0
122409     479.0     395.0    466.0    1100.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
1                           0.0                     2.0
2                           0.0                     2.0
3                           0.0                     0.0
4                           0.0                     0.0
5                           3.0                     0.0
...                         ...                     ...
122405                      1.0                     1.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
1                                0.0                          0.0
2                                0.0                          0.0
3                                0.0                          0.0
4                                0.0                          0.0
5                                1.0                          0.0
...                              ...                          ...
122405                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
1                             0.0                       0.0
2                             0.0                       0.0
3                             0.0                       0.0
4                             0.0                       0.0
5                             0.0                       0.0
...                           ...                       ...
122405                        0.0                       0.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
1                           0.0                     0.0            CT
2                           0.0                     0.0            CT
3                           0.0                     0.0            CT
4                           0.0                     0.0            CT
5                           0.0                     0.0            CT
...                         ...                     ...           ...
122405                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[122409 rows x 97 columns]

In [ ]:
# 7. Todas las filas, hasta la fila 3
ej_7 = df_CS.loc[:3]
print(ej_7)

   time_left  ct_score  t_score       map  bomb_planted  ct_health  t_health  \
0     175.00       0.0      0.0  de_dust2         False      500.0     500.0
1     156.03       0.0      0.0  de_dust2         False      500.0     500.0
2      96.03       0.0      0.0  de_dust2         False      391.0     400.0
3      76.03       0.0      0.0  de_dust2         False      391.0     400.0

   ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0       0.0      0.0    4000.0  ...                  0.0
1     400.0    300.0     600.0  ...                  0.0
2     294.0    200.0     750.0  ...                  0.0
3     294.0    200.0     750.0  ...                  0.0

   ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                      0.0                     0.0
1                      0.0                     2.0
2                      0.0                     2.0
3                      0.0                     0.0

   ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                           0.0                          0.0
1                           0.0                          0.0
2                           0.0                          0.0
3                           0.0                          0.0

   ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                        0.0                       0.0
1                        0.0                       0.0
2                        0.0                       0.0
3                        0.0                       0.0

   ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
0                      0.0                     0.0            CT
1                      0.0                     0.0            CT
2                      0.0                     0.0            CT
3                      0.0                     0.0            CT

[4 rows x 97 columns]

In [ ]:
# 8. Múltiples filas consecutivas
ej_8 = df_CS.loc[2:5]
print(ej_8)

   time_left  ct_score  t_score       map  bomb_planted  ct_health  t_health  \
2      96.03       0.0      0.0  de_dust2         False      391.0     400.0
3      76.03       0.0      0.0  de_dust2         False      391.0     400.0
4     174.97       1.0      0.0  de_dust2         False      500.0     500.0
5     114.97       1.0      0.0  de_dust2         False      500.0     500.0

   ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
2     294.0    200.0     750.0  ...                  0.0
3     294.0    200.0     750.0  ...                  0.0
4     192.0      0.0   18350.0  ...                  0.0
5     500.0      0.0    1750.0  ...                  0.0

   ct_grenade_smokegrenade  t_grenade_smokegrenade  \
2                      0.0                     2.0
3                      0.0                     0.0
4                      0.0                     0.0
5                      3.0                     0.0

   ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
2                           0.0                          0.0
3                           0.0                          0.0
4                           0.0                          0.0
5                           1.0                          0.0

   ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
2                        0.0                       0.0
3                        0.0                       0.0
4                        0.0                       0.0
5                        0.0                       0.0

   ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
2                      0.0                     0.0            CT
3                      0.0                     0.0            CT
4                      0.0                     0.0            CT
5                      0.0                     0.0            CT

[4 rows x 97 columns]

9. Crea 4 ejercicios con indexación booleana

In [ ]:
# 1. Mostrar rondas donde el equipo CT tiene más de 10 puntos
filtro_1 = df_CS[df_CS['ct_score'] > 10]
print(filtro_1)

        time_left  ct_score  t_score        map  bomb_planted  ct_health  \
235        169.95      11.0     12.0  de_mirage         False      500.0
236        170.00      11.0     12.0  de_mirage         False      500.0
237        163.14      11.0     12.0  de_mirage         False      500.0
238        103.14      11.0     12.0  de_mirage         False      500.0
239         83.14      11.0     12.0  de_mirage         False      408.0
...           ...       ...      ...        ...           ...        ...
122405      15.41      11.0     14.0   de_train          True      200.0
122406     174.93      11.0     15.0   de_train         False      500.0
122407     114.93      11.0     15.0   de_train         False      500.0
122408      94.93      11.0     15.0   de_train         False      500.0
122409      74.93      11.0     15.0   de_train         False      375.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
235        500.0     197.0      0.0   18000.0  ...                  0.0
236        500.0     500.0      0.0    6300.0  ...                  0.0
237        500.0     500.0    200.0    4500.0  ...                  1.0
238        500.0     500.0    400.0    2350.0  ...                  0.0
239        292.0     498.0    197.0    3250.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122405     242.0     195.0    359.0     100.0  ...                  2.0
122406     500.0      95.0    175.0   11500.0  ...                  2.0
122407     500.0     495.0    475.0    1200.0  ...                  4.0
122408     500.0     495.0    475.0    1200.0  ...                  5.0
122409     479.0     395.0    466.0    1100.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
235                         1.0                     0.0
236                         3.0                     0.0
237                         4.0                     0.0
238                         4.0                     0.0
239                         2.0                     0.0
...                         ...                     ...
122405                      1.0                     1.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
235                              0.0                          0.0
236                              1.0                          0.0
237                              2.0                          0.0
238                              2.0                          0.0
239                              1.0                          0.0
...                              ...                          ...
122405                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
235                           0.0                       0.0
236                           0.0                       0.0
237                           0.0                       0.0
238                           0.0                       0.0
239                           0.0                       0.0
...                           ...                       ...
122405                        0.0                       0.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
235                         0.0                     0.0            CT
236                         0.0                     0.0            CT
237                         0.0                     0.0            CT
238                         0.0                     0.0            CT
239                         0.0                     0.0            CT
...                         ...                     ...           ...
122405                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[28886 rows x 97 columns]

In [ ]:
# 2. Mostrar rondas donde la bomba SÍ ha sido plantada
filtro_2 = df_CS[df_CS['bomb_planted'] == True]
print(filtro_2)

        time_left  ct_score  t_score       map  bomb_planted  ct_health  \
20          29.27       2.0      1.0  de_dust2          True      379.0
26          22.70       3.0      1.0  de_dust2          True      100.0
33          37.38       3.0      2.0  de_dust2          True      300.0
34          17.38       3.0      2.0  de_dust2          True      300.0
39          24.84       3.0      3.0  de_dust2          True       67.0
...           ...       ...      ...       ...           ...        ...
122390      12.26      10.0     13.0  de_train          True      180.0
122399      20.27      11.0     13.0  de_train          True      174.0
122400       0.24      11.0     13.0  de_train          True      119.0
122404      35.41      11.0     14.0  de_train          True      315.0
122405      15.41      11.0     14.0  de_train          True      200.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
20          99.0     487.0     93.0    2050.0  ...                  0.0
26         149.0     100.0    175.0    1050.0  ...                  0.0
33         414.0     300.0    441.0     250.0  ...                  1.0
34         414.0     300.0    441.0     250.0  ...                  1.0
39           0.0      96.0      0.0    2150.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122390       0.0     197.0      0.0    1150.0  ...                  0.0
122399     239.0     200.0    284.0    2000.0  ...                  1.0
122400     178.0     182.0    195.0    2300.0  ...                  0.0
122404     428.0     382.0    467.0     150.0  ...                  2.0
122405     242.0     195.0    359.0     100.0  ...                  2.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
20                          0.0                     0.0
26                          1.0                     0.0
33                          1.0                     2.0
34                          1.0                     3.0
39                          0.0                     0.0
...                         ...                     ...
122390                      1.0                     0.0
122399                      0.0                     0.0
122400                      0.0                     0.0
122404                      2.0                     3.0
122405                      1.0                     1.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
20                               0.0                          0.0
26                               0.0                          0.0
33                               0.0                          0.0
34                               0.0                          0.0
39                               0.0                          0.0
...                              ...                          ...
122390                           0.0                          0.0
122399                           0.0                          0.0
122400                           0.0                          0.0
122404                           0.0                          0.0
122405                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
20                            0.0                       0.0
26                            0.0                       0.0
33                            0.0                       2.0
34                            0.0                       1.0
39                            0.0                       0.0
...                           ...                       ...
122390                        0.0                       0.0
122399                        0.0                       0.0
122400                        0.0                       0.0
122404                        0.0                       0.0
122405                        0.0                       0.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
20                          0.0                     0.0            CT
26                          0.0                     0.0             T
33                          0.0                     0.0             T
34                          0.0                     0.0             T
39                          0.0                     0.0            CT
...                         ...                     ...           ...
122390                      0.0                     0.0            CT
122399                      0.0                     0.0             T
122400                      0.0                     0.0             T
122404                      0.0                     0.0             T
122405                      0.0                     0.0             T

[13684 rows x 97 columns]

In [ ]:
# 3. Mostrar rondas donde el tiempo restante sea menor a 60 segundos
filtro_3 = df_CS[df_CS['time_left'] < 60]
print(filtro_3)

        time_left  ct_score  t_score       map  bomb_planted  ct_health  \
8           54.97       1.0      0.0  de_dust2         False      249.0
13          54.97       2.0      0.0  de_dust2         False      116.0
14          34.97       2.0      0.0  de_dust2         False      100.0
19          54.97       2.0      1.0  de_dust2         False      391.0
20          29.27       2.0      1.0  de_dust2          True      379.0
...           ...       ...      ...       ...           ...        ...
122398      33.38      11.0     13.0  de_train         False      216.0
122399      20.27      11.0     13.0  de_train          True      174.0
122400       0.24      11.0     13.0  de_train          True      119.0
122404      35.41      11.0     14.0  de_train          True      315.0
122405      15.41      11.0     14.0  de_train          True      200.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
8           89.0     269.0      0.0    2300.0  ...                  0.0
13         126.0     187.0    179.0    1050.0  ...                  0.0
14         105.0     100.0    174.0     300.0  ...                  0.0
19         211.0     489.0    323.0    1150.0  ...                  0.0
20          99.0     487.0     93.0    2050.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122398     239.0     297.0    284.0    2700.0  ...                  2.0
122399     239.0     200.0    284.0    2000.0  ...                  1.0
122400     178.0     182.0    195.0    2300.0  ...                  0.0
122404     428.0     382.0    467.0     150.0  ...                  2.0
122405     242.0     195.0    359.0     100.0  ...                  2.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
8                           1.0                     0.0
13                          0.0                     1.0
14                          0.0                     1.0
19                          0.0                     1.0
20                          0.0                     0.0
...                         ...                     ...
122398                      1.0                     0.0
122399                      0.0                     0.0
122400                      0.0                     0.0
122404                      2.0                     3.0
122405                      1.0                     1.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
8                                0.0                          0.0
13                               0.0                          0.0
14                               0.0                          0.0
19                               0.0                          0.0
20                               0.0                          0.0
...                              ...                          ...
122398                           0.0                          0.0
122399                           0.0                          0.0
122400                           0.0                          0.0
122404                           0.0                          0.0
122405                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
8                             0.0                       0.0
13                            0.0                       0.0
14                            0.0                       0.0
19                            0.0                       0.0
20                            0.0                       0.0
...                           ...                       ...
122398                        0.0                       0.0
122399                        0.0                       0.0
122400                        0.0                       0.0
122404                        0.0                       0.0
122405                        0.0                       0.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
8                           0.0                     0.0            CT
13                          0.0                     0.0             T
14                          0.0                     0.0             T
19                          0.0                     0.0            CT
20                          0.0                     0.0            CT
...                         ...                     ...           ...
122398                      0.0                     0.0             T
122399                      0.0                     0.0             T
122400                      0.0                     0.0             T
122404                      0.0                     0.0             T
122405                      0.0                     0.0             T

[36631 rows x 97 columns]

In [ ]:
# 4. Mostrar rondas donde la bomba NO ha sido plantada Y el equipo T tiene más de 5 puntos
filtro_4 = df_CS[(df_CS['bomb_planted'] == False) & (df_CS['t_score'] > 5)]
print(filtro_4)

        time_left  ct_score  t_score       map  bomb_planted  ct_health  \
80         175.00       4.0     11.0  de_dust2         False      500.0
81         156.38       4.0     11.0  de_dust2         False      500.0
82          96.38       4.0     11.0  de_dust2         False      320.0
83          76.38       4.0     11.0  de_dust2         False      116.0
84         174.96       4.0     12.0  de_dust2         False      500.0
...           ...       ...      ...       ...           ...        ...
122403      94.93      11.0     14.0  de_train         False      500.0
122406     174.93      11.0     15.0  de_train         False      500.0
122407     114.93      11.0     15.0  de_train         False      500.0
122408      94.93      11.0     15.0  de_train         False      500.0
122409      74.93      11.0     15.0  de_train         False      375.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
80         500.0       0.0      0.0    4000.0  ...                  0.0
81         500.0     300.0    200.0    1250.0  ...                  3.0
82         461.0     384.0    179.0     600.0  ...                  3.0
83         366.0     197.0    151.0     300.0  ...                  1.0
84         500.0       0.0    151.0   10100.0  ...                  1.0
...          ...       ...      ...       ...  ...                  ...
122403     500.0     476.0    477.0     500.0  ...                  2.0
122406     500.0      95.0    175.0   11500.0  ...                  2.0
122407     500.0     495.0    475.0    1200.0  ...                  4.0
122408     500.0     495.0    475.0    1200.0  ...                  5.0
122409     479.0     395.0    466.0    1100.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
80                          0.0                     1.0
81                          0.0                     0.0
82                          0.0                     0.0
83                          0.0                     0.0
84                          0.0                     0.0
...                         ...                     ...
122403                      3.0                     3.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
80                               0.0                          0.0
81                               0.0                          0.0
82                               0.0                          0.0
83                               0.0                          0.0
84                               0.0                          0.0
...                              ...                          ...
122403                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
80                            0.0                       0.0
81                            0.0                       0.0
82                            0.0                       0.0
83                            0.0                       0.0
84                            0.0                       0.0
...                           ...                       ...
122403                        0.0                       3.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
80                          0.0                     0.0            CT
81                          0.0                     1.0             T
82                          0.0                     0.0             T
83                          0.0                     0.0             T
84                          0.0                     0.0             T
...                         ...                     ...           ...
122403                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[60553 rows x 97 columns]

10.Muestra el valor mínimo, valor máximo, promedio, desviación estándar y media de
una columna(elige la columna)

In [ ]:
Minimo = df_CS['ct_score'].min()
print(Minimo)

0.0

In [ ]:
Maximo = df_CS['ct_score'].max()
print(Maximo)

32.0

In [ ]:
Promedio = df_CS['ct_score'].mean()
print(Promedio)

6.709239441222122

In [ ]:
Desviacion = df_CS['ct_score'].std()
print(Desviacion)

4.790362330615361

In [ ]:
Media = df_CS['ct_score'].median()
print(Media)

6.0

11.Muestra cuántos valores ausentes existen en el df

In [ ]:
Ausentes= df_CS.isna().sum()
print(Ausentes)

time_left                    0
ct_score                     0
t_score                      0
map                          0
bomb_planted                 0
                            ..
ct_grenade_molotovgrenade    0
t_grenade_molotovgrenade     0
ct_grenade_decoygrenade      0
t_grenade_decoygrenade       0
round_winner                 0
Length: 97, dtype: int64

12. Sustituye los valores nulos de la columna ( tipo de columna numérico, elija la col)

In [ ]:
df_CS['time_left'] = df_CS['time_left'].fillna(0)
print(df_CS['time_left'])

0         175.00
1         156.03
2          96.03
3          76.03
4         174.97
           ...
122405     15.41
122406    174.93
122407    114.93
122408     94.93
122409     74.93
Name: time_left, Length: 122410, dtype: float64

13. Sustituye los valores nulos de la columna ( tipo de columna object, elija la col)

In [ ]:
df_CS['map'] = df_CS['map'].fillna('Desconocido')
print(df_CS['map'])

0         de_dust2
1         de_dust2
2         de_dust2
3         de_dust2
4         de_dust2
            ...
122405    de_train
122406    de_train
122407    de_train
122408    de_train
122409    de_train
Name: map, Length: 122410, dtype: object

14. Elimina las filas con valores nulos (elige 2 columnas)

In [ ]:
df_CS = df_CS.dropna(subset=['ct_score', 't_score'])
print(df_CS)

        time_left  ct_score  t_score       map  bomb_planted  ct_health  \
0          175.00       0.0      0.0  de_dust2         False      500.0
1          156.03       0.0      0.0  de_dust2         False      500.0
2           96.03       0.0      0.0  de_dust2         False      391.0
3           76.03       0.0      0.0  de_dust2         False      391.0
4          174.97       1.0      0.0  de_dust2         False      500.0
...           ...       ...      ...       ...           ...        ...
122405      15.41      11.0     14.0  de_train          True      200.0
122406     174.93      11.0     15.0  de_train         False      500.0
122407     114.93      11.0     15.0  de_train         False      500.0
122408      94.93      11.0     15.0  de_train         False      500.0
122409      74.93      11.0     15.0  de_train         False      375.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0          500.0       0.0      0.0    4000.0  ...                  0.0
1          500.0     400.0    300.0     600.0  ...                  0.0
2          400.0     294.0    200.0     750.0  ...                  0.0
3          400.0     294.0    200.0     750.0  ...                  0.0
4          500.0     192.0      0.0   18350.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122405     242.0     195.0    359.0     100.0  ...                  2.0
122406     500.0      95.0    175.0   11500.0  ...                  2.0
122407     500.0     495.0    475.0    1200.0  ...                  4.0
122408     500.0     495.0    475.0    1200.0  ...                  5.0
122409     479.0     395.0    466.0    1100.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0
1                           0.0                     2.0
2                           0.0                     2.0
3                           0.0                     0.0
4                           0.0                     0.0
...                         ...                     ...
122405                      1.0                     1.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0
1                                0.0                          0.0
2                                0.0                          0.0
3                                0.0                          0.0
4                                0.0                          0.0
...                              ...                          ...
122405                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0
1                             0.0                       0.0
2                             0.0                       0.0
3                             0.0                       0.0
4                             0.0                       0.0
...                           ...                       ...
122405                        0.0                       0.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
0                           0.0                     0.0            CT
1                           0.0                     0.0            CT
2                           0.0                     0.0            CT
3                           0.0                     0.0            CT
4                           0.0                     0.0            CT
...                         ...                     ...           ...
122405                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[122410 rows x 97 columns]

Punto 15: Elimina todas las columnas con valores nulos

In [ ]:
df_CS = df_CS.dropna(axis=1)
print(df_CS)

        time_left  ct_score  t_score       map  bomb_planted  ct_health  \
0          175.00       0.0      0.0  de_dust2         False      500.0
1          156.03       0.0      0.0  de_dust2         False      500.0
2           96.03       0.0      0.0  de_dust2         False      391.0
3           76.03       0.0      0.0  de_dust2         False      391.0
4          174.97       1.0      0.0  de_dust2         False      500.0
...           ...       ...      ...       ...           ...        ...
122405      15.41      11.0     14.0  de_train          True      200.0
122406     174.93      11.0     15.0  de_train         False      500.0
122407     114.93      11.0     15.0  de_train         False      500.0
122408      94.93      11.0     15.0  de_train         False      500.0
122409      74.93      11.0     15.0  de_train         False      375.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0          500.0       0.0      0.0    4000.0  ...                  0.0
1          500.0     400.0    300.0     600.0  ...                  0.0
2          400.0     294.0    200.0     750.0  ...                  0.0
3          400.0     294.0    200.0     750.0  ...                  0.0
4          500.0     192.0      0.0   18350.0  ...                  0.0
...          ...       ...      ...       ...  ...                  ...
122405     242.0     195.0    359.0     100.0  ...                  2.0
122406     500.0      95.0    175.0   11500.0  ...                  2.0
122407     500.0     495.0    475.0    1200.0  ...                  4.0
122408     500.0     495.0    475.0    1200.0  ...                  5.0
122409     479.0     395.0    466.0    1100.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0
1                           0.0                     2.0
2                           0.0                     2.0
3                           0.0                     0.0
4                           0.0                     0.0
...                         ...                     ...
122405                      1.0                     1.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0
1                                0.0                          0.0
2                                0.0                          0.0
3                                0.0                          0.0
4                                0.0                          0.0
...                              ...                          ...
122405                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0
1                             0.0                       0.0
2                             0.0                       0.0
3                             0.0                       0.0
4                             0.0                       0.0
...                           ...                       ...
122405                        0.0                       0.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
0                           0.0                     0.0            CT
1                           0.0                     0.0            CT
2                           0.0                     0.0            CT
3                           0.0                     0.0            CT
4                           0.0                     0.0            CT
...                         ...                     ...           ...
122405                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[122410 rows x 97 columns]

Punto 16: Elimina una columna específica

In [ ]:
df_CS = df_CS.drop(columns=['bomb_planted'], errors='ignore')
print(df_CS.columns)

Index(['time_left', 'ct_score', 't_score', 'map', 'ct_health', 't_health',
       'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets', 't_helmets',
       'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev', 'ct_weapon_nova', 't_weapon_nova',
       'ct_weapon_p90', 't_weapon_p90', 'ct_weapon_r8revolver',
       't_weapon_r8revolver', 'ct_weapon_sawedoff', 't_weapon_sawedoff',
       'ct_weapon_scar20', 't_weapon_scar20', 'ct_weapon_sg553',
       't_weapon_sg553', 'ct_weapon_ssg08', 't_weapon_ssg08',
       'ct_weapon_ump45', 't_weapon_ump45', 'ct_weapon_xm1014',
       't_weapon_xm1014', 'ct_weapon_deagle', 't_weapon_deagle',
       'ct_weapon_fiveseven', 't_weapon_fiveseven', 'ct_weapon_usps',
       't_weapon_usps', 'ct_weapon_p250', 't_weapon_p250', 'ct_weapon_p2000',
       't_weapon_p2000', 'ct_weapon_tec9', 't_weapon_tec9',
       'ct_grenade_hegrenade', 't_grenade_hegrenade', 'ct_grenade_flashbang',
       't_grenade_flashbang', 'ct_grenade_smokegrenade',
       't_grenade_smokegrenade', 'ct_grenade_incendiarygrenade',
       't_grenade_incendiarygrenade', 'ct_grenade_molotovgrenade',
       't_grenade_molotovgrenade', 'ct_grenade_decoygrenade',
       't_grenade_decoygrenade', 'round_winner'],
      dtype='object')

Punto 17: Muestra el total de duplicados en el df

In [ ]:
total_duplicados = df_CS.duplicated().sum()
print(total_duplicados)

4962

Punto 18: Elimina los duplicados

In [ ]:
df_CS = df_CS.drop_duplicates()
print(df_CS)

        time_left  ct_score  t_score       map  ct_health  t_health  ct_armor  \
0          175.00       0.0      0.0  de_dust2      500.0     500.0       0.0
1          156.03       0.0      0.0  de_dust2      500.0     500.0     400.0
2           96.03       0.0      0.0  de_dust2      391.0     400.0     294.0
3           76.03       0.0      0.0  de_dust2      391.0     400.0     294.0
4          174.97       1.0      0.0  de_dust2      500.0     500.0     192.0
...           ...       ...      ...       ...        ...       ...       ...
122405      15.41      11.0     14.0  de_train      200.0     242.0     195.0
122406     174.93      11.0     15.0  de_train      500.0     500.0      95.0
122407     114.93      11.0     15.0  de_train      500.0     500.0     495.0
122408      94.93      11.0     15.0  de_train      500.0     500.0     495.0
122409      74.93      11.0     15.0  de_train      375.0     479.0     395.0

        t_armor  ct_money  t_money  ...  t_grenade_flashbang  \
0           0.0    4000.0   4000.0  ...                  0.0
1         300.0     600.0    650.0  ...                  0.0
2         200.0     750.0    500.0  ...                  0.0
3         200.0     750.0    500.0  ...                  0.0
4           0.0   18350.0  10750.0  ...                  0.0
...         ...       ...      ...  ...                  ...
122405    359.0     100.0   5950.0  ...                  2.0
122406    175.0   11500.0  23900.0  ...                  2.0
122407    475.0    1200.0   6700.0  ...                  4.0
122408    475.0    1200.0   6700.0  ...                  5.0
122409    466.0    1100.0   7000.0  ...                  3.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                           0.0                     0.0
1                           0.0                     2.0
2                           0.0                     2.0
3                           0.0                     0.0
4                           0.0                     0.0
...                         ...                     ...
122405                      1.0                     1.0
122406                      1.0                     0.0
122407                      3.0                     5.0
122408                      0.0                     3.0
122409                      0.0                     2.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                                0.0                          0.0
1                                0.0                          0.0
2                                0.0                          0.0
3                                0.0                          0.0
4                                0.0                          0.0
...                              ...                          ...
122405                           0.0                          0.0
122406                           0.0                          0.0
122407                           1.0                          0.0
122408                           0.0                          0.0
122409                           0.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                             0.0                       0.0
1                             0.0                       0.0
2                             0.0                       0.0
3                             0.0                       0.0
4                             0.0                       0.0
...                           ...                       ...
122405                        0.0                       0.0
122406                        0.0                       0.0
122407                        0.0                       5.0
122408                        0.0                       4.0
122409                        0.0                       3.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
0                           0.0                     0.0            CT
1                           0.0                     0.0            CT
2                           0.0                     0.0            CT
3                           0.0                     0.0            CT
4                           0.0                     0.0            CT
...                         ...                     ...           ...
122405                      0.0                     0.0             T
122406                      0.0                     0.0             T
122407                      0.0                     0.0             T
122408                      0.0                     0.0             T
122409                      0.0                     0.0             T

[117448 rows x 96 columns]

Punto 19: Muestra los valores únicos de la columna

In [ ]:
valores_unicos = df_CS['map'].unique()
print(valores_unicos)

['de_dust2' 'de_mirage' 'de_nuke' 'de_inferno' 'de_overpass' 'de_vertigo'
 'de_train' 'de_cache']

Punto 20: Asigna en la variable el número de valores únicos

In [ ]:
num_unicos = df_CS['map'].nunique()
print(num_unicos)

8

Punto 21: Agrupa por la columna y calcula cuántas filas tiene ese grupo

In [ ]:
agrupacion_filas = df_CS.groupby('map').size()
print(agrupacion_filas)

map
de_cache         145
de_dust2       21252
de_inferno     22982
de_mirage      17793
de_nuke        18078
de_overpass    13474
de_train       12919
de_vertigo     10805
dtype: int64

Punto 22: Agrupa por la columna y calcula la suma total de ese grupo

In [ ]:
suma_total_grupo = df_CS.groupby('map')['ct_score'].sum()
print(suma_total_grupo)

map
de_cache         1050.0
de_dust2       145511.0
de_inferno     152400.0
de_mirage      121899.0
de_nuke        123253.0
de_overpass     89246.0
de_train        88584.0
de_vertigo      73129.0
Name: ct_score, dtype: float64

Sort

In [ ]:

print(df_CS.sort_values(by='time_left', ascending=True))

       time_left  ct_score  t_score         map  bomb_planted  ct_health  \
81800       0.01      11.0     11.0   de_mirage          True      200.0
32874       0.02       1.0      5.0  de_inferno          True      248.0
3749        0.03       0.0      1.0    de_train          True      200.0
50752       0.03      11.0      6.0   de_mirage          True      100.0
54184       0.03       0.0      0.0  de_vertigo          True      100.0
...          ...       ...      ...         ...           ...        ...
91083     175.00       7.0      8.0     de_nuke         False      500.0
91084     175.00       7.0      8.0     de_nuke         False      500.0
91085     175.00       7.0      8.0     de_nuke         False      500.0
91086     175.00       7.0      8.0     de_nuke         False      500.0
91087     175.00       7.0      8.0     de_nuke         False      500.0

       t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
81800     400.0     200.0    334.0     100.0  ...                  1.0
32874     365.0     100.0    362.0    7050.0  ...                  2.0
3749        0.0     200.0      0.0     450.0  ...                  0.0
50752     300.0     100.0    300.0    1850.0  ...                  1.0
54184       0.0     100.0      0.0     450.0  ...                  0.0
...         ...       ...      ...       ...  ...                  ...
91083     500.0       0.0    200.0    4000.0  ...                  1.0
91084     500.0       0.0    200.0    4000.0  ...                  1.0
91085     500.0       0.0    300.0    4000.0  ...                  1.0
91086     500.0     100.0    300.0    3350.0  ...                  1.0
91087     500.0     300.0    300.0    2050.0  ...                  1.0

       ct_grenade_smokegrenade  t_grenade_smokegrenade  \
81800                      2.0                     1.0
32874                      0.0                     1.0
3749                       0.0                     0.0
50752                      0.0                     0.0
54184                      0.0                     0.0
...                        ...                     ...
91083                      0.0                     0.0
91084                      0.0                     0.0
91085                      0.0                     0.0
91086                      0.0                     0.0
91087                      0.0                     0.0

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
81800                           0.0                          0.0
32874                           0.0                          0.0
3749                            0.0                          0.0
50752                           0.0                          0.0
54184                           0.0                          0.0
...                             ...                          ...
91083                           0.0                          0.0
91084                           0.0                          0.0
91085                           0.0                          0.0
91086                           0.0                          0.0
91087                           0.0                          0.0

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
81800                        0.0                       2.0
32874                        0.0                       1.0
3749                         0.0                       0.0
50752                        0.0                       0.0
54184                        0.0                       0.0
...                          ...                       ...
91083                        0.0                       1.0
91084                        0.0                       1.0
91085                        0.0                       1.0
91086                        0.0                       1.0
91087                        0.0                       1.0

       ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
81800                      0.0                     0.0             T
32874                      0.0                     0.0             T
3749                       0.0                     0.0             T
50752                      0.0                     0.0             T
54184                      0.0                     0.0             T
...                        ...                     ...           ...
91083                      0.0                     0.0             T
91084                      0.0                     0.0             T
91085                      0.0                     0.0             T
91086                      0.0                     0.0             T
91087                      0.0                     0.0             T

[122410 rows x 97 columns]

In [ ]:
print(df_CS.sort_values(by='time_left').head(10))

        time_left  ct_score  t_score          map  bomb_planted  ct_health  \
81800        0.01      11.0     11.0    de_mirage          True      200.0
32874        0.02       1.0      5.0   de_inferno          True      248.0
3749         0.03       0.0      1.0     de_train          True      200.0
50752        0.03      11.0      6.0    de_mirage          True      100.0
54184        0.03       0.0      0.0   de_vertigo          True      100.0
39291        0.03      14.0     14.0    de_mirage          True      100.0
100532       0.04      13.0     13.0    de_mirage          True      252.0
55611        0.04       7.0     11.0  de_overpass          True       72.0
57717        0.04       5.0      3.0   de_inferno          True       44.0
35740        0.04      13.0      7.0   de_vertigo          True      200.0

        t_health  ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
81800      400.0     200.0    334.0     100.0  ...                  1.0
32874      365.0     100.0    362.0    7050.0  ...                  2.0
3749         0.0     200.0      0.0     450.0  ...                  0.0
50752      300.0     100.0    300.0    1850.0  ...                  1.0
54184        0.0     100.0      0.0     450.0  ...                  0.0
39291      491.0      96.0    495.0     300.0  ...                  0.0
100532     250.0     278.0    372.0     200.0  ...                  1.0
55611      271.0     100.0    372.0    1900.0  ...                  0.0
57717      130.0     100.0    149.0     400.0  ...                  0.0
35740      329.0     197.0    394.0   12350.0  ...                  1.0

        ct_grenade_smokegrenade  t_grenade_smokegrenade  \
81800                       2.0                     1.0
32874                       0.0                     1.0
3749                        0.0                     0.0
50752                       0.0                     0.0
54184                       0.0                     0.0
39291                       0.0                     2.0
100532                      0.0                     0.0
55611                       0.0                     0.0
57717                       1.0                     0.0
35740                       0.0                     0.0

        ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
81800                            0.0                          0.0
32874                            0.0                          0.0
3749                             0.0                          0.0
50752                            0.0                          0.0
54184                            0.0                          0.0
39291                            0.0                          0.0
100532                           0.0                          0.0
55611                            0.0                          0.0
57717                            0.0                          0.0
35740                            1.0                          0.0

        ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
81800                         0.0                       2.0
32874                         0.0                       1.0
3749                          0.0                       0.0
50752                         0.0                       0.0
54184                         0.0                       0.0
39291                         0.0                       0.0
100532                        0.0                       0.0
55611                         0.0                       0.0
57717                         0.0                       0.0
35740                         0.0                       0.0

        ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner
81800                       0.0                     0.0             T
32874                       0.0                     0.0             T
3749                        0.0                     0.0             T
50752                       0.0                     0.0             T
54184                       0.0                     0.0             T
39291                       0.0                     0.0             T
100532                      0.0                     0.0             T
55611                       0.0                     0.0             T
57717                       0.0                     0.0             T
35740                       0.0                     0.0             T

[10 rows x 97 columns]

Consulta con Query

In [ ]:
df_score = df_CS.query("ct_score < 15")[['ct_score', 't_score']]
df_score

        ct_score  t_score
0            0.0      0.0
1            0.0      0.0
2            0.0      0.0
3            0.0      0.0
4            1.0      0.0
...          ...      ...
122405      11.0     14.0
122406      11.0     15.0
122407      11.0     15.0
122408      11.0     15.0
122409      11.0     15.0

[115197 rows x 2 columns]

In [ ]:
df_time = df_CS.query("time_left > 60")[['time_left', 'map']]
df_time

        time_left       map
0          175.00  de_dust2
1          156.03  de_dust2
2           96.03  de_dust2
3           76.03  de_dust2
4          174.97  de_dust2
...           ...       ...
122403      94.93  de_train
122406     174.93  de_train
122407     114.93  de_train
122408      94.93  de_train
122409      74.93  de_train

[85778 rows x 2 columns]

Isin y ~ Isin

In [ ]:
lista_mapas = ['de_dust2', 'de_mirage', 'de_inferno']
df_lista = df_CS[df_CS['map'].isin(lista_mapas)][['map', 'time_left', 'ct_score', 't_score']]
print(df_lista)

             map  time_left  ct_score  t_score
0       de_dust2     175.00       0.0      0.0
1       de_dust2     156.03       0.0      0.0
2       de_dust2      96.03       0.0      0.0
3       de_dust2      76.03       0.0      0.0
4       de_dust2     174.97       1.0      0.0
...          ...        ...       ...      ...
121840  de_dust2      74.95      18.0     17.0
121841  de_dust2      54.95      18.0     17.0
121842  de_dust2      34.95      18.0     17.0
121843  de_dust2      14.95      18.0     17.0
121844  de_dust2      31.41      18.0     17.0

[64531 rows x 4 columns]

In [ ]:
mapas_a_excluir = ['de_dust2', 'de_mirage']
df_resultado = df_CS[~df_CS['map'].isin(mapas_a_excluir)][['map', 'time_left', 'ct_score', 't_score']]
print(df_resultado)

             map  time_left  ct_score  t_score
475      de_nuke     175.00       0.0      0.0
476      de_nuke     157.78       0.0      0.0
477      de_nuke      97.78       0.0      0.0
478      de_nuke      77.78       0.0      0.0
479      de_nuke     174.96       0.0      1.0
...          ...        ...       ...      ...
122405  de_train      15.41      11.0     14.0
122406  de_train     174.93      11.0     15.0
122407  de_train     114.93      11.0     15.0
122408  de_train      94.93      11.0     15.0
122409  de_train      74.93      11.0     15.0

[81690 rows x 4 columns]

In [ ]:
#Ej.1
def round_phase(time_left):

    if time_left >= 120:
      return 'alto'
    elif time_left >= 60:
      return 'medio'
    elif time_left <= 60:
      return 'bajo'
    else:
        return 'unknown'

In [ ]:
df_CS['round_phase'] = df_CS['time_left'].apply(round_phase)
print(df_CS['round_phase'])

0          alto
1          alto
2         medio
3         medio
4          alto
          ...
122405     bajo
122406     alto
122407    medio
122408    medio
122409    medio
Name: round_phase, Length: 122410, dtype: object

In [ ]:
df_CS['round_phase'].value_counts()

round_phase
medio    52064
bajo     36631
alto     33715
Name: count, dtype: int64